---
- hosts: dev
   #become: yes
   #become_user: root
   #become_method: sudo
    #sudo: yes
   #remote_user: root
  tasks:
   - name: create file
     file:
       path: /home/ubuntu/hello3
       state: directory
       mode: 0777
